apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-deployment
  name: redis-deployment
  namespace: giropops
spec:
  replicas: 10
  selector:
    matchLabels:
      app: redis-deployment
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
      - image: redis:latest
        name: redis
        resources:
          limits: 
            cpu: 0.5
            memory: 256Mi
          requests:
            cpu: 0.3
            memory: 128Mi
        livenessProbe: 
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3  
          successThreshold: 1
        startupProbe:
          tcpSocket: 
            port: 6379  
          initialDelaySeconds: 15
          timeoutSeconds: 5
          failureThreshold: 1
          successThreshold: 1  