apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops-senhas
  name: giropops-senhas
spec:
  containers: 
  - image: giropops-senhas
    name: giropops-senhas
    ports:
    - containerPort: 5000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
